language: node_js

node_js:
  - "4.1"
before_install:
  - git submodule update --remote

before_script:
  - npm install -g gulp
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - gulp build
  - npm test

after_success:
  - npm run codecov
