language: node_js

dist: trusty
sudo: false

addons:
  chrome: stable

cache:
  yarn: true
  directories:
    - node_modules

node_js:
  - "8.7"

stages:
  - test


install:
  - yarn install


script: gulp build

jobs:
  include:
    - stage: test
      script: npm run test:coverage


after_success:
  - npm run codecov