language: node_js

node_js:
  - "4.1"

install:
  - sudo $(which npm) install
  - sudo $(which npm) install -g gulp
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - gulp build
  - npm test
after_success:
  - npm run codecov
