language: node_js

addons:
  chrome: stable

cache:
  yarn: true
  directories:
    - node_modules

node_js:
  - "8.7"

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

install:
  - yarn install
script:
  - gulp build
  - npm run test:coverage
after_success:
  - npm run codecov