language: node_js

node_js:
  - "8.4"

before_install:
  - npm install -g typescript@next
  - npm install -g rollup
  - npm install -g typescript-formatter

install:
  - npm install
  - npm install -g gulp
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - gulp build
  - gulp testInCI
after_success:
  - npm run codecov
