language: node_js

addons:
  chrome: stable

cache:
  yarn: true
  directories:
    - node_modules

node_js:
  - "8.7"

install:
  - yarn install
script:
  - gulp build
  - npm run test:ci
after_success:
  - npm run codecov