language: node_js
dist: trusty
sudo: false
addons:
  chrome: stable
cache:
  yarn: true
  directories:
  - node_modules
node_js:
- '8.7'
install:
- yarn install
script:
- gulp build
- npm run test:coverage
deploy:
  provider: releases
  api_key:
    secure: Qc8srQOlKxmqB1ggBppgKlGuMj/xRYsn1KiDDb30uIhZyVQKna30noLZobB03jduuWmeixC5L761o8ZcOB6e5tcr05/Cmue/cB2S8SmsYiIA0BpKB5/gvT0iORzP5GBblLxajFPMf/FXVaF7e9qm3BGonRudc14yXSjQcLpzMds=
  file_glob: true
  file: dist/*
  skip_cleanup: true
  overwrite: true
  on:
    tags: false
after_success:
- npm run codecov
