language: node_js
dist: trusty
sudo: false
addons:
  chrome: stable
cache:
  yarn: true
  directories:
  - node_modules
node_js:
- '8.7'

install:
- yarn install


jobs:
  include:
    - stage: test
      script: npm run test:renderCI
    # - stage: test
    #   script: npm run test:pfCI

    - stage: test
      env:
        global:
          - CC_TEST_REPORTER_ID=864730435b2a0b3d8f054495c28797d2f838803f3f710c95b23a947535e1e178


      script: npm run test:ci



      before_script:
        - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        - chmod +x ./cc-test-reporter
        - ./cc-test-reporter before-build


      after_script:
        - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT -t lcov -d -r 864730435b2a0b3d8f054495c28797d2f838803f3f710c95b23a947535e1e178



    - stage: deploy
      script: npm run buildAll:ci
      deploy:
        provider: releases
        api_key:
          secure: TJSUZ+WTiYMNjOW+VJoIDBNxZ12aXte/8GtPPo87bVNUeBo3PGimVdVgaQsV5s4FJN58U70hdIXcPQROpnL9Wi/BXFA2ylE0E8AKskQj1Exqs4vnugmFDdqPIENunMuHwHF7aUcE7DPvpFA6SfhhiY7U8OfiF5VGhQmelstkUf8=
        skip_cleanup: true
        overwrite: true
        file: dist/*.js
        on:
          repo: Wonder-Technology/Wonder.js
          branch: master
          tags: true